export type SourceFetchConfig = {
  id: number;
  source_site_id: number;
  fetch_name: string;
  fetch_url: string;
  http_method: string;
  auth_type: string;
  auth_username: string | null;
  request_headers_json: string | null;
  query_params_json: string | null;
  content_path: string | null;
  title_field: string | null;
  slug_field: string | null;
  content_field: string | null;
  excerpt_field: string | null;
  published_at_field: string | null;
  modified_at_field: string | null;
  featured_image_field: string | null;
  source_id_field: string | null;
  status_field: string | null;
  category_field: string | null;
  tag_field: string | null;
  is_active: boolean;
  created_at?: string;
  updated_at?: string;
};

export type SourceFetchConfigPayload = {
  source_site_id: number;
  fetch_name: string;
  fetch_url: string;
  http_method: string;
  auth_type: string;
  auth_username: string;
  auth_password_encrypted: string;
  auth_token_encrypted: string;
  request_headers_json: string;
  query_params_json: string;
  content_path: string;
  title_field: string;
  slug_field: string;
  content_field: string;
  excerpt_field: string;
  published_at_field: string;
  modified_at_field: string;
  featured_image_field: string;
  source_id_field: string;
  status_field: string;
  category_field: string;
  tag_field: string;
  is_active: boolean;
};
