"""create initial core tables

Revision ID: 1b0dc33d3b14
Revises: 
Create Date: 2026-03-06 17:25:55.216510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1b0dc33d3b14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('ollama_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('auth_username', sa.String(length=255), nullable=True),
    sa.Column('auth_password_encrypted', sa.Text(), nullable=True),
    sa.Column('auth_token_encrypted', sa.Text(), nullable=True),
    sa.Column('custom_headers_json', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ollama_profiles_id'), 'ollama_profiles', ['id'], unique=False)
    op.create_table('source_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('site_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_language', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_sites_id'), 'source_sites', ['id'], unique=False)
    op.create_table('source_fetch_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_site_id', sa.Integer(), nullable=False),
    sa.Column('fetch_name', sa.String(length=255), nullable=False),
    sa.Column('fetch_url', sa.String(length=1000), nullable=False),
    sa.Column('http_method', sa.String(length=20), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('auth_username', sa.String(length=255), nullable=True),
    sa.Column('auth_password_encrypted', sa.Text(), nullable=True),
    sa.Column('auth_token_encrypted', sa.Text(), nullable=True),
    sa.Column('request_headers_json', sa.Text(), nullable=True),
    sa.Column('query_params_json', sa.Text(), nullable=True),
    sa.Column('content_path', sa.String(length=500), nullable=True),
    sa.Column('title_field', sa.String(length=255), nullable=True),
    sa.Column('slug_field', sa.String(length=255), nullable=True),
    sa.Column('content_field', sa.String(length=255), nullable=True),
    sa.Column('excerpt_field', sa.String(length=255), nullable=True),
    sa.Column('published_at_field', sa.String(length=255), nullable=True),
    sa.Column('modified_at_field', sa.String(length=255), nullable=True),
    sa.Column('featured_image_field', sa.String(length=255), nullable=True),
    sa.Column('source_id_field', sa.String(length=255), nullable=True),
    sa.Column('status_field', sa.String(length=255), nullable=True),
    sa.Column('category_field', sa.String(length=255), nullable=True),
    sa.Column('tag_field', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_site_id'], ['source_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_fetch_configs_id'), 'source_fetch_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_fetch_configs_id'), table_name='source_fetch_configs')
    op.drop_table('source_fetch_configs')
    op.drop_index(op.f('ix_source_sites_id'), table_name='source_sites')
    op.drop_table('source_sites')
    op.drop_index(op.f('ix_ollama_profiles_id'), table_name='ollama_profiles')
    op.drop_table('ollama_profiles')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
