"""add posts tables

Revision ID: a6c4fee687e3
Revises: ac169879f607
Create Date: 2026-03-07 00:53:16.453604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a6c4fee687e3'
down_revision: Union[str, Sequence[str], None] = 'ac169879f607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
