"""add posts tables

Revision ID: ac169879f607
Revises: c84fca2aff1b
Create Date: 2026-03-07 00:49:25.505570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ac169879f607'
down_revision: Union[str, Sequence[str], None] = 'c84fca2aff1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_site_id', sa.Integer(), nullable=False),
    sa.Column('fetch_config_id', sa.Integer(), nullable=True),
    sa.Column('external_post_id', sa.String(length=255), nullable=False),
    sa.Column('external_post_url', sa.String(length=1000), nullable=True),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('clean_content', sa.Text(), nullable=True),
    sa.Column('featured_image_url', sa.String(length=1000), nullable=True),
    sa.Column('categories_json', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_publish_status', sa.String(length=50), nullable=True),
    sa.Column('original_published_at', sa.DateTime(), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(), nullable=True),
    sa.Column('first_fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('is_deleted_in_source', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fetch_config_id'], ['source_fetch_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_site_id'], ['source_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_external_post_id'), 'posts', ['external_post_id'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=False)
    op.create_table('post_content_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.String(length=50), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_content_versions_id'), 'post_content_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_content_versions_id'), table_name='post_content_versions')
    op.drop_table('post_content_versions')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_external_post_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
