"""add user profile fields

Revision ID: bcc331b0846c
Revises: 37eb30e51b17
Create Date: 2026-03-14 22:55:29.422412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'bcc331b0846c'
down_revision: Union[str, Sequence[str], None] = '37eb30e51b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('git_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('x_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'facebook_url')
    op.drop_column('users', 'x_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'git_url')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
