"""add user profile fields

Revision ID: bf15d58f0c17
Revises: bcc331b0846c
Create Date: 2026-03-14 23:04:44.388227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'bf15d58f0c17'
down_revision: Union[str, Sequence[str], None] = 'bcc331b0846c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
