"""add posts tables

Revision ID: c84fca2aff1b
Revises: 1b0dc33d3b14
Create Date: 2026-03-07 00:46:20.140537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c84fca2aff1b'
down_revision: Union[str, Sequence[str], None] = '1b0dc33d3b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
